INSERT OR IGNORE INTO brands (name_en, name_ko, search_keywords) VALUES
('Nike','나이키','nike 나이키 나'),
('Jordan','조던','jordan 조던'),
('Adidas','아디다스','adidas 아디다스'),
('Yeezy','이지','yeezy 이지'),
('New Balance','뉴발란스','new balance 뉴발란스'),
('Converse','컨버스','converse 컨버스'),
('Vans','반스','vans 반스'),
('Asics','아식스','asics 아식스'),
('Puma','퓨마','puma 퓨마'),
('Reebok','리복','reebok 리복'),
('Salomon','살로몬','salomon 살로몬'),
('Saucony','사코니','saucony 사코니'),
('Brooks','브룩스','brooks 브룩스'),
('On Running','온러닝','on running 온러닝'),
('Hoka','호카','hoka 호카'),
('Mizuno','미즈노','mizuno 미즈노'),
('Timberland','팀버랜드','timberland 팀버랜드'),
('UGG','어그','ugg 어그'),
('Dr. Martens','닥터마틴','dr martens 닥터마틴'),
('Birkenstock','버켄스탁','birkenstock 버켄스탁'),
('Crocs','크록스','crocs 크록스'),
('Clarks','클락스','clarks 클락스'),
('New Era','뉴에라','new era 뉴에라'),
('Fila','휠라','fila 휠라'),
('Supreme','슈프림','supreme 슈프림'),
('Off-White','오프화이트','off-white off white 오프화이트'),
('Palace','팔라스','palace 팔라스'),
('Stüssy','스투시','stussy 스투시'),
('BAPE','베이프','bape 베이프 a bathing ape'),
('Anti Social Social Club','ASSC','anti social social club assc'),
('Kith','키스','kith 키스'),
('Fear of God','피어오브갓','fear of god fog 피어오브갓'),
('Essentials','에센셜','essentials 에센셜'),
('Stone Island','스톤아일랜드','stone island 스톤아일랜드'),
('CP Company','씨피컴퍼니','cp company 씨피컴퍼니'),
('Carhartt WIP','칼하트','carhartt wip 칼하트'),
('Human Made','휴먼메이드','human made 휴먼메이드'),
('Neighborhood','네이버후드','neighborhood 네이버후드'),
('Undercover','언더커버','undercover 언더커버'),
('Ader Error','아더에러','ader error 아더에러'),
('Covernat','커버낫','covernat 커버낫'),
('Louis Vuitton','루이비통','louis vuitton lv 루이비통'),
('Chanel','샤넬','chanel 샤넬'),
('Gucci','구찌','gucci 구찌'),
('Prada','프라다','prada 프라다'),
('Hermès','에르메스','hermes hermès 에르메스'),
('Dior','디올','dior 디올'),
('Balenciaga','발렌시아가','balenciaga 발렌시아가'),
('Saint Laurent','생로랑','saint laurent ysl 생로랑'),
('Givenchy','지방시','givenchy 지방시'),
('Bottega Veneta','보테가베네타','bottega veneta bv 보테가베네타'),
('Valentino','발렌티노','valentino 발렌티노'),
('Versace','베르사체','versace 베르사체'),
('Burberry','버버리','burberry 버버리'),
('Fendi','펜디','fendi 펜디'),
('Celine','셀린느','celine 셀린느'),
('Loewe','로에베','loewe 로에베'),
('Alexander McQueen','알렉산더맥퀸','alexander mcqueen 알렉산더맥퀸'),
('Moncler','몽클레르','moncler 몽클레르'),
('Canada Goose','캐나다구스','canada goose 캐나다구스'),
('Maison Margiela','메종마르지엘라','maison margiela mm6 메종마르지엘라'),
('Rick Owens','릭오웬스','rick owens 릭오웬스'),
('Ami Paris','아미파리','ami paris 아미파리'),
('Jacquemus','자크뮈스','jacquemus 자크뮈스'),
('The North Face','노스페이스','the north face tnf 노스페이스'),
('Arc''teryx','아크테릭스','arcteryx arc teryx 아크테릭스'),
('Patagonia','파타고니아','patagonia 파타고니아'),
('Columbia','컬럼비아','columbia 컬럼비아'),
('Ralph Lauren','랄프로렌','ralph lauren polo 랄프로렌'),
('Tommy Hilfiger','타미힐피거','tommy hilfiger 타미힐피거'),
('Calvin Klein','캘빈클라인','calvin klein ck 캘빈클라인'),
('Lacoste','라코스테','lacoste 라코스테'),
('Champion','챔피언','champion 챔피언'),
('Levi''s','리바이스','levis 리바이스'),
('Diesel','디젤','diesel 디젤'),
('Carhartt','칼하트','carhartt 칼하트'),
('Rolex','롤렉스','rolex 롤렉스'),
('Omega','오메가','omega 오메가'),
('Patek Philippe','파텍필립','patek philippe 파텍필립'),
('Audemars Piguet','오데마피게','audemars piguet ap 오데마피게'),
('Cartier','까르띠에','cartier 까르띠에 카르티에'),
('IWC','아이더블유씨','iwc 아이더블유씨'),
('Breitling','브라이틀링','breitling 브라이틀링'),
('TAG Heuer','태그호이어','tag heuer 태그호이어'),
('Longines','론진','longines 론진'),
('Seiko','세이코','seiko 세이코'),
('Grand Seiko','그랜드세이코','grand seiko 그랜드세이코'),
('Casio','카시오','casio 카시오'),
('G-Shock','지샥','g-shock g shock 지샥'),
('Richard Mille','리샤르밀','richard mille 리샤르밀'),
('Hublot','위블로','hublot 위블로'),
('Panerai','파네라이','panerai 파네라이'),
('Apple','애플','apple 애플'),
('Samsung','삼성','samsung 삼성'),
('Sony','소니','sony 소니'),
('Bose','보스','bose 보스'),
('Bang & Olufsen','뱅앤올룹슨','bang olufsen bo 뱅앤올룹슨'),
('Dyson','다이슨','dyson 다이슨'),
('Nintendo','닌텐도','nintendo 닌텐도'),
('Beats','비츠','beats 비츠'),
('Tiffany & Co.','티파니','tiffany 티파니'),
('Bulgari','불가리','bulgari bvlgari 불가리'),
('Van Cleef & Arpels','반클리프아펠','van cleef arpels vca 반클리프아펠'),
('MLB','엠엘비','mlb 엠엘비'),
('Descente','데상트','descente 데상트'),
('Matin Kim','마뗑킴','matin kim 마뗑킴'),
('Wooyoungmi','우영미','wooyoungmi 우영미'),
('Nau','나우','nau 나우');
